from pathlib import Path

path = Path("public/app.js")
text = path.read_text(encoding="utf-8")

anchor = '    providerStatus: null,\n    loadingMoreSenses: false,'
replacement = '    providerStatus: null,\n    providerChecks: { dictionary:null, ai:null },\n    loadingMoreSenses: false,'
assert anchor in text, "state providerStatus anchor missing"
text = text.replace(anchor, replacement, 1)

anchor = '''    const selectedModel=codex?.selectedModel||"";\n    const selectedEffort=codex?.selectedReasoningEffort||"";\n\n    return shell('''
replacement = '''    const selectedModel=codex?.selectedModel||"";\n    const selectedEffort=codex?.selectedReasoningEffort||"";\n    const dictionaryCheck=state.providerChecks?.dictionary||null;\n    const aiCheck=state.providerChecks?.ai||null;\n    const dictLocalReady=Boolean(dict?.localAvailable);\n    const dictKeySaved=Boolean(dict?.fallbackConfigured);\n    const dictMaskedKey=String(dict?.maskedKey||"");\n    const runtimeTest=codex?.runtimeTest||{};\n    const aiChecking=aiCheck?.status==="checking";\n    const aiPassed=!aiChecking&&(aiCheck?.status==="passed"||runtimeTest.status==="passed");\n    const aiFailed=!aiChecking&&(aiCheck?.status==="failed"||runtimeTest.status==="failed");\n    const aiReadyForTest=Boolean(codex?.cliAvailable&&codex?.authFound);\n    const formatCheckTime=value=>{\n      if(!value)return "";\n      try{return new Date(value).toLocaleString();}catch{return String(value);}\n    };\n    const runtimeMessage=aiCheck?.message||runtimeTest.message||"";\n    const runtimeAt=aiCheck?.at||runtimeTest.at||"";\n\n    return shell('''
assert anchor in text, "settings variable anchor missing"
text = text.replace(anchor, replacement, 1)

old_dict = '''        <div class="setting-row">\n          <div>\n            <h3>词典增强</h3>\n            <p>基础查词可离线使用。连接在线词典后，可补充真人发音和更多例句。</p>\n          </div>\n          <div style="display:flex;gap:8px;flex-wrap:wrap">\n            <input class="input" id="mw-api-key" type="password" style="width:250px" placeholder="输入词典服务密钥" />\n            <button class="btn primary" data-action="save-dictionary-key">保存</button>\n            <button class="btn" data-action="test-dictionary">验证</button>\n          </div>\n        </div>'''
new_dict = '''        <div class="setting-row" style="align-items:flex-start">\n          <div style="min-width:310px;flex:1">\n            <h3>词典增强</h3>\n            <p>本地 Core + ECDICT 负责快速查词；在线词典只用于真人发音和例句增强。</p>\n            <div style="display:flex;gap:7px;flex-wrap:wrap;margin-top:10px">\n              <span class="pill ${dictLocalReady?"green":"red"}">${dictLocalReady?"本地词典已就绪":"本地词典未就绪"}</span>\n              <span class="pill ${dictKeySaved?"green":"amber"}">${dictKeySaved?`在线密钥已保存${dictMaskedKey?` · ${escapeHtml(dictMaskedKey)}`:""}`:"在线增强未配置"}</span>\n              ${dictionaryCheck?.status==="checking"?`<span class="pill amber">正在验证在线词典…</span>`:dictionaryCheck?.status==="passed"?`<span class="pill green">✓ ${escapeHtml(dictionaryCheck.message||"在线增强可用")}</span>`:dictionaryCheck?.status==="failed"?`<span class="pill red">! ${escapeHtml(dictionaryCheck.message||"在线增强验证失败")}</span>`:""}\n            </div>\n          </div>\n          <div style="display:flex;gap:8px;flex-wrap:wrap;align-items:flex-end">\n            <input class="input" id="mw-api-key" type="password" style="width:250px" placeholder="${dictKeySaved?"已保存密钥；输入新密钥可替换":"输入词典服务密钥"}" />\n            <button class="btn primary" data-action="save-dictionary-key">${dictKeySaved?"更新密钥":"保存密钥"}</button>\n            <button class="btn" data-action="test-dictionary" ${dictionaryCheck?.status==="checking"?"disabled":""}>${dictionaryCheck?.status==="checking"?"验证中…":"验证连接"}</button>\n          </div>\n        </div>'''
assert old_dict in text, "dictionary settings row missing"
text = text.replace(old_dict, new_dict, 1)

old_ai = '''        <div class="setting-row" style="align-items:flex-start">\n          <div style="min-width:310px;flex:1">\n            <h3>AI 辅助</h3>\n            <p>用于造句反馈、联想场景和图片生成。</p>\n          </div>\n          <div class="setting-actions-inline">\n            <span class="pill ${codex?.cliAvailable?"green":"red"}">${codex?.cliAvailable?"已连接":"未连接"}</span>\n            ${codex?.cliAvailable?"":`<button class="btn" data-action="test-codex-text">重新连接</button>`}\n          </div>\n        </div>'''
new_ai = '''        <div class="setting-row" style="align-items:flex-start">\n          <div style="min-width:310px;flex:1">\n            <h3>AI 辅助</h3>\n            <p>用于整段表达查询、造句反馈、联想场景和图片生成。CLI 存在不等于真实连接成功，以“运行验证”为准。</p>\n            <div style="display:flex;gap:7px;flex-wrap:wrap;margin-top:10px">\n              <span class="pill ${codex?.cliAvailable?"green":"red"}">${codex?.cliAvailable?"CLI 已检测":"CLI 未检测"}</span>\n              <span class="pill ${codex?.authFound?"green":"red"}">${codex?.authFound?"已登录":"未检测到登录"}</span>\n              <span class="pill blue">模型 · ${escapeHtml(codex?.effectiveModel||selectedModel||"gpt-5.6-luna")}</span>\n              <span class="pill ${aiChecking?"amber":aiPassed?"green":aiFailed?"red":aiReadyForTest?"amber":"red"}">${aiChecking?"正在验证 AI…":aiPassed?"✓ 运行连接已验证":aiFailed?"! 运行连接失败":aiReadyForTest?"等待运行验证":"当前不可连接"}</span>\n            </div>\n            <div style="margin-top:8px;color:var(--muted);font-size:11px;line-height:1.55">${runtimeMessage?escapeHtml(runtimeMessage):"尚未进行真实 AI 请求验证。"}${runtimeAt?` · ${escapeHtml(formatCheckTime(runtimeAt))}`:""}${codex?.fastTextTransport?.state?` · Fast transport: ${escapeHtml(codex.fastTextTransport.state)}`:""}</div>\n          </div>\n          <div class="setting-actions-inline">\n            <button class="btn ${aiPassed?"":"primary"}" data-action="test-codex-text" ${aiChecking?"disabled":""}>${aiChecking?"正在检查…":aiPassed?"重新检查连接":"检查 AI 连接"}</button>\n          </div>\n        </div>'''
assert old_ai in text, "AI settings row missing"
text = text.replace(old_ai, new_ai, 1)

old_dict_test = '''    if(action==="test-dictionary"){\n      try{\n        const payload=await api("/api/dictionary/test",{method:"POST",body:{}});\n        toast(payload.message||"在线词典增强可用");\n      }catch(err){showErrorNotice(err,"在线词典增强连接没有成功");}\n      return;\n    }'''
new_dict_test = '''    if(action==="test-dictionary"){\n      state.providerChecks.dictionary={status:"checking",message:"正在验证在线词典…",at:""};\n      render();\n      try{\n        const payload=await api("/api/dictionary/test",{method:"POST",body:{}});\n        state.providerChecks.dictionary={status:"passed",message:payload.message||"在线词典增强可用",at:new Date().toISOString()};\n      }catch(err){\n        state.providerChecks.dictionary={status:"failed",message:err?.userError?.message||err?.message||"在线词典增强连接没有成功",at:new Date().toISOString()};\n      }finally{\n        await refreshProviderStatus(true);\n        render();\n      }\n      return;\n    }'''
assert old_dict_test in text, "dictionary test handler missing"
text = text.replace(old_dict_test, new_dict_test, 1)

old_ai_test = '''    if(action==="test-codex-text"){\n      toast("正在检查 AI 连接…");\n      try{\n        const payload=await api("/api/ai/test",{method:"POST",body:{}});\n        toast(payload.test?.message||"AI 连接正常");\n      }catch(err){\n        showErrorNotice(err,"AI 连接检查失败");\n      }finally{\n        await refreshProviderStatus(true);\n      }\n      return;\n    }'''
new_ai_test = '''    if(action==="test-codex-text"){\n      state.providerChecks.ai={status:"checking",message:"正在发起真实 AI 请求…",at:""};\n      render();\n      try{\n        const payload=await api("/api/ai/test",{method:"POST",body:{}});\n        state.providerChecks.ai={status:payload.test?.status==="passed"?"passed":"failed",message:payload.test?.message||"AI 连接正常",at:payload.test?.at||new Date().toISOString()};\n      }catch(err){\n        state.providerChecks.ai={status:"failed",message:err?.userError?.message||err?.message||"AI 连接检查失败",at:new Date().toISOString()};\n      }finally{\n        await refreshProviderStatus(true);\n        render();\n      }\n      return;\n    }'''
assert old_ai_test in text, "AI test handler missing"
text = text.replace(old_ai_test, new_ai_test, 1)

path.write_text(text, encoding="utf-8")

contract_path = Path("scripts/check-runtime-authority-v3.js")
contract = contract_path.read_text(encoding="utf-8")
old_contract = 'assert(app.includes("基础查词可离线使用。连接在线词典后，可补充真人发音和更多例句。"),"app.js base Settings copy must describe local-first dictionary behavior");'
new_contract = '''assert(app.includes("本地 Core + ECDICT 负责快速查词；在线词典只用于真人发音和例句增强。"),"Settings must explain the actual local-first dictionary architecture");\nassert(app.includes("dictMaskedKey")&&app.includes("在线密钥已保存")&&app.includes("本地词典已就绪"),"Settings must expose saved dictionary-key and local dictionary readiness without revealing the credential");\nassert(app.includes("providerChecks: { dictionary:null, ai:null }")&&app.includes("正在验证在线词典…")&&app.includes("在线增强验证失败"),"dictionary verification state must stay visibly persisted on the Settings page");\nassert(app.includes("CLI 已检测")&&app.includes("未检测到登录")&&app.includes("runtimeTest")&&app.includes("fastTextTransport"),"AI Settings must distinguish CLI, auth, real runtime verification, and fast transport state");\nassert(app.includes("正在发起真实 AI 请求…")&&app.includes("运行连接已验证")&&app.includes("运行连接失败"),"AI connection checks must have visible checking/success/failure states rather than toast-only feedback");'''
assert old_contract in contract, "old Settings authority contract missing"
contract = contract.replace(old_contract, new_contract, 1)
contract_path.write_text(contract, encoding="utf-8")

print("settings status V4 migration and authority contract applied")
