from pathlib import Path

root=Path(__file__).resolve().parents[1]
today=root/'public/today-plan-v3.js'
select=root/'public/select-stage-v3.js'
today_check=root/'scripts/check-today-plan-v3.js'
stage_check=root/'scripts/check-stage-renderers-v3.js'

s=today.read_text(encoding='utf-8')

s=s.replace('  let libraryFilter = "all";\n','  let libraryFilter = "all";\n  let adoptingFreshCard = false;\n  const ADD_INTENT_KEY = "lexiflow:today-add-intent-v4";\n')

s=s.replace('  function primaryHtml(plan){\n', '''  function markTodayAddIntent(){\n    try{sessionStorage.setItem(ADD_INTENT_KEY,String(Date.now()));}catch{}\n  }\n  function todayAddIntentStartedAt(){\n    try{\n      const value=Number(sessionStorage.getItem(ADD_INTENT_KEY)||0);\n      if(!value||Date.now()-value>30*60*1000){sessionStorage.removeItem(ADD_INTENT_KEY);return 0;}\n      return value;\n    }catch{return 0;}\n  }\n  function clearTodayAddIntent(){try{sessionStorage.removeItem(ADD_INTENT_KEY);}catch{}}\n\n  function primaryHtml(plan){\n''')

s=s.replace('if(Number(plan.remainingSelectSlots||0)>0&&!(latestData?.cards||[]).length)return `<button class="btn primary" data-route="add">添加第一个单词</button>`;\n    if(Number(plan.remainingSelectSlots||0)>0)return `<button class="btn primary" data-route="add">继续添加新词</button>`;', 'if(Number(plan.remainingSelectSlots||0)>0&&!(latestData?.cards||[]).length)return `<button class="btn primary" data-route="add" data-tp-add-today="1">添加第一个单词</button>`;\n    if(Number(plan.remainingSelectSlots||0)>0)return `<button class="btn primary" data-route="add" data-tp-add-today="1">继续添加新词</button>`;')

s=s.replace('    if(save&&!document.querySelector(".study-card-focus")){setText(save,"保存到单词库");save.title="保存后会出现在单词库的“待学习”中，由你决定哪天加入 Today";}','    if(save&&!document.querySelector(".study-card-focus")){\n      if(todayAddIntentStartedAt()){setText(save,"保存并加入今日学习");save.title="保存后直接完成今日选词，下一学习日开始记忆";}\n      else{setText(save,"保存到单词库");save.title="保存后会进入待学习列表";}\n    }')

old='''  async function selectFromPending(id){\n    if(saving)return false;saving=true;\n    try{\n      await refresh();const next=core.normalizeData(JSON.parse(JSON.stringify(latestData||{}))), plan=next.dailyPlan;\n      if(Number(plan.remainingSelectSlots||0)<=0)return false;\n      const card=next.cards.find(item=>item.id===id);if(!card||card.stage!=="select"||!card.inboxPending)return false;\n      const now=new Date();card.inboxPending=false;card.todaySelectedOn=core.dayKey(now);card.stageEligibleOn=now.toISOString();card.inboxSelectedAt=now.toISOString();card.updatedAt=now.toISOString();\n      next.activities=Array.isArray(next.activities)?next.activities:[];next.activities.push({id:uid(),type:"library-selected",cardId:card.id,at:now.toISOString(),authority:"today-plan-v3"});\n      await persist(next,"library-selected");location.reload();return true;\n    }finally{saving=false;}\n  }\n'''
new='''  function completeSelection(next,card,now,source="library"){\n    const day=core.dayKey(now),prev={...card,learningStage:"select"};\n    card.inboxPending=false;\n    card.todaySelectedOn=day;\n    card.selectedOn=day;\n    card.inboxSelectedAt=now.toISOString();\n    card.selectCompletedOn=now.toISOString();\n    card.stage="memorize";\n    card.learningStage="memorize";\n    Object.assign(card,core.crossDayPatch(prev,{stage:"memorize",learningStage:"memorize"},now)||{});\n    card.updatedAt=now.toISOString();\n    next.activities=Array.isArray(next.activities)?next.activities:[];\n    next.activities.push({id:uid(),type:"library-selected",cardId:card.id,at:now.toISOString(),authority:"today-plan-v3",source});\n    next.activities.push({id:uid(),type:"stage-complete",cardId:card.id,stage:"select",nextStage:"memorize",at:now.toISOString(),authority:"today-plan-v3",source});\n  }\n\n  async function selectFromPending(id,source="library"){\n    if(saving)return false;saving=true;\n    try{\n      await refresh();const next=core.normalizeData(JSON.parse(JSON.stringify(latestData||{}))), plan=next.dailyPlan||core.buildDailyPlan(next);\n      if(Number(plan.remainingSelectSlots||0)<=0)return false;\n      const card=next.cards.find(item=>item.id===id);if(!card||core.canonicalStage(card)!=="select"||!card.inboxPending)return false;\n      const now=new Date();completeSelection(next,card,now,source);\n      await persist(next,source==="today-add"?"today-add-complete-select":"library-selected-complete-select");location.reload();return true;\n    }finally{saving=false;}\n  }\n\n  async function adoptFreshTodayCard(){\n    if(adoptingFreshCard||saving)return false;\n    const startedAt=todayAddIntentStartedAt();if(!startedAt)return false;\n    syncFromGateway();\n    const plan=latestData?.dailyPlan||core.buildDailyPlan(latestData||{});\n    if(Number(plan?.remainingSelectSlots||0)<=0){clearTodayAddIntent();return false;}\n    const card=(latestData?.cards||[])\n      .filter(item=>core.canonicalStage(item)==="select"&&item.inboxPending===true&&new Date(item.createdAt||0).getTime()>=startedAt-1000)\n      .sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0))[0];\n    if(!card)return false;\n    clearTodayAddIntent();adoptingFreshCard=true;\n    try{return await selectFromPending(card.id,"today-add");}\n    finally{adoptingFreshCard=false;}\n  }\n'''
if old not in s: raise SystemExit('selectFromPending anchor missing')
s=s.replace(old,new)

s=s.replace('''    const route=String(routeButton.dataset.route||"").trim();\n    if(!route)return false;\n''','''    const route=String(routeButton.dataset.route||"").trim();\n    if(!route)return false;\n    if(routeButton.dataset.tpAddToday==="1")markTodayAddIntent();\n''')

s=s.replace('''      syncFromGateway();\n      decorate();\n''','''      syncFromGateway();\n      decorate();\n      void adoptFreshTodayCard();\n''')

s=s.replace('''    if(latestData)decorate();else void refreshAndDecorate(true);\n''','''    if(latestData){decorate();void adoptFreshTodayCard();}else void refreshAndDecorate(true).then(()=>void adoptFreshTodayCard());\n''')

today.write_text(s,encoding='utf-8')

s=select.read_text(encoding='utf-8')
s=s.replace('.lexi-select-v3-example{padding-top:11px;border-top:1px solid var(--line);line-height:1.65}.lexi-select-v3-example p{margin:4px 0 0;color:var(--muted)}', '.lexi-select-v3-example{padding-top:11px;border-top:1px solid var(--line);line-height:1.65}.lexi-select-v3-example-line{display:flex;align-items:flex-start;gap:8px}.lexi-select-v3-example-line>span{flex:1}.lexi-select-v3-example-line button{border:0;background:transparent;cursor:pointer;font-size:16px;line-height:1.4}.lexi-select-v3-example p{margin:4px 0 0;color:var(--muted)}')
s=s.replace('${card.exampleEn?`<div class="lexi-select-v3-example"><div>${esc(card.exampleEn)}</div>${card.exampleZh?`<p>${esc(card.exampleZh)}</p>`:""}</div>`:""}', '${card.exampleEn?`<div class="lexi-select-v3-example"><div class="lexi-select-v3-example-line"><span>${esc(card.exampleEn)}</span><button type="button" data-select-v3="speak-example" aria-label="播放例句">🔊</button></div>${card.exampleZh?`<p>${esc(card.exampleZh)}</p>`:""}</div>`:""}')
old='''  async function speak(){\n    const card=currentCard();if(!card)return;\n    try{if(typeof window.LexiFlowNaturalTts?.play==="function"&&await window.LexiFlowNaturalTts.play(card.word))return;}catch{}\n    try{const utterance=new SpeechSynthesisUtterance(card.word);utterance.lang="en-US";speechSynthesis.cancel();speechSynthesis.speak(utterance);}catch{}\n  }\n\n  document.addEventListener("click",event=>{\n    const button=event.target?.closest?.('[data-select-v3="speak"]');\n    if(!button)return;\n    event.preventDefault();event.stopImmediatePropagation();void speak();\n  },true);\n'''
new='''  async function playAudio(src){\n    return new Promise((resolve,reject)=>{const audio=new Audio(src);audio.onended=resolve;audio.onerror=reject;audio.play().catch(reject);});\n  }\n\n  async function speakWord(){\n    const card=currentCard();if(!card)return;\n    const segments=[];if(card.audioUrl)segments.push(card.audioUrl);if(Array.isArray(card.audioUrls))segments.push(...card.audioUrls);\n    if(segments.length){\n      try{for(const src of Array.from(new Set(segments.filter(Boolean))))await playAudio(src);return;}catch{}\n    }\n    try{if(typeof window.LexiFlowNaturalTts?.play==="function"&&await window.LexiFlowNaturalTts.play(card.word))return;}catch{}\n  }\n\n  async function speakExample(){\n    const card=currentCard();if(!card?.exampleEn)return;\n    try{if(typeof window.LexiFlowNaturalTts?.play==="function")await window.LexiFlowNaturalTts.play(card.exampleEn);}catch{}\n  }\n\n  document.addEventListener("click",event=>{\n    const button=event.target?.closest?.('[data-select-v3]');\n    if(!button)return;\n    const action=button.dataset.selectV3;if(action!=="speak"&&action!=="speak-example")return;\n    event.preventDefault();event.stopImmediatePropagation();\n    if(action==="speak")void speakWord();else void speakExample();\n  },true);\n'''
if old not in s: raise SystemExit('select speak anchor missing')
s=s.replace(old,new)
select.write_text(s,encoding='utf-8')

s=today_check.read_text(encoding='utf-8')
s=s.replace('assert(source.includes("selectFromPending")&&source.includes("moveBackToPending"),"Word Library must explicitly own adding/removing Pending words from Today");', 'assert(source.includes("selectFromPending")&&source.includes("moveBackToPending"),"Word Library must explicitly own adding/removing Pending words from Today");\nassert(source.includes("function completeSelection(next,card,now"),"choosing a new word must complete Select in the same learner decision instead of requiring a second Today confirmation");\nassert(source.includes("card.stage=\\\"memorize\\\"")&&source.includes("core.crossDayPatch"),"completed selection must schedule Memorize for the next StudyDay");\nassert(source.includes("data-tp-add-today=\\\"1\\\"")&&source.includes("adoptFreshTodayCard"),"Today add flow must auto-adopt a freshly created card without a Word Library detour");')
today_check.write_text(s,encoding='utf-8')

s=stage_check.read_text(encoding='utf-8')
s=s.replace('assert(select.includes("LexiFlowStudyRenderer?.currentCardId"),"Select renderer must bind to explicit Study Session card identity");', 'assert(select.includes("LexiFlowStudyRenderer?.currentCardId"),"Select renderer must bind to explicit Study Session card identity");\nassert(select.includes("card.audioUrl")&&select.includes("card.audioUrls")&&select.includes("LexiFlowNaturalTts?.play"),"Select word pronunciation must use the same saved dictionary-audio then natural-TTS order as the card-creation surface");\nassert(select.includes(\'data-select-v3="speak-example"\')&&select.includes("card.exampleEn"),"Select confirmation must provide natural playback for the reference example");\nassert(!select.includes("SpeechSynthesisUtterance"),"Select must not silently fall back to a different browser voice source");')
stage_check.write_text(s,encoding='utf-8')

print('selection/pronunciation migration applied')
